### ISSUE TITLE
It's not possible override sass variables ($breakpoints-... and $print) 

### ISSUE THREAD

**Issue by farin** [inkline/nuxt-module-inkline#8]
Breakpoints are sass variable 
As nuxt module prepens css to config options with
`options.css = ['@inkline/inkline/inkline.scss'].concat(options.css || []);`

there is no place to override $breakpoints-xxl ... etc.
define in app.vue or file nuxtConfig/options/css is too late

**Comment by alexgrozav** [comment]
Good point! The concat should obviously be the other way around. Updated in 3.1.2!  :).

**Comment by farin** [comment]
That was fast. Thanks for all your work.

**Comment by alexgrozav** [comment]
Sorry, an update here. Looks like this backfired a little.

Instead of inverting the concat, I've added two configuration options that allow you to essentially achieve what you wanted here.

| Property              | Type     | Description                                                     |
|-----------------------|----------|-----------------------------------------------------------------|
| inkline.css           | Boolean  | Enable or disable adding Inkline's stylesheet automatically.    |
| inkline.sassVariables | String[] | Paths to SCSS Variables to prepend before Inkline's stylesheet. |

**Comment by tasiotas** [comment]
how should we use `sassVariables` ?
is it supposed to point to scss file with local variables?

Modal (or anything else) doesn't pickup this color defined in main.scss

nuxt.config.js
```js
export default defineNuxtConfig({
  inkline: {
    css: true,
    sassVariables: ['~/assets/css/main.scss'],
    components: {},
    colorMode: 'light',
  },
})
```

main.scss
```js
@import '@inkline/inkline/css/variables';
@import '@inkline/inkline/css/mixins';

@include i-modal() {
  ----wrapper--background: rgba(166, 66, 66, 0.25);
}
```
